language: node_js
node_js: '8'
jobs:
  include:
  - stage: Deploy to npm
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email: telegraph.engineering@telegraph.co.uk
      api_key:
        secure: T3BpLpXlzHbbOGuHhF8VLM5ZBZzcDOwVB8DYHFa/KLrsGuPEl9K8ZIxByBFuxXProk1DFWNsuUkUkb2c+raWigjwsBa75UuiUKf+TFrQu2093imJlDw1pNZpctg03/8ri/TknaJIJtlHm3CJMWBo3HMvqx0ZvNkYY3ou2tX3scSEZ5I433rcH8p/jCymYW5OKiFc8U5/apq0yAL0RNXBDOOlWGwr2RwnDIbXvhf0V3HdsIj9Jjudgm98HanUSDkRBEyYsBkKjwfJ1jcLf8mjL1mSx8tggi3wZ7EubAU7q22kIEwmemGp6nDLfjfcq38c9Zwjr3A8kTFtURhJHIHPXWgAEKEy7qbrSpsjtv171vFn5DAGZn2Bo1xgtOqFAMMC9GUNppWgTw9vbfntd4F0oMyxUVQsRHRwMobLbcBRNdudffJtLHo8ZQJ8Uc9n3zQej75uGCfzLNxahr8MvnCeuD1LWBojSkhEDBVC6JaXhZAUoh2pOVP4wceSeY8vBvbFpBhchiDrZUdVnb7hA04+TY4IfeiB6r6Y7VbIzH2Sg9YMu9h4OCIx6+JsXDs25XglU1vyuVUdP6G8I/Z3jHg5oAuCTVvv5oSR2OlszkkygVhTf7htQe+IIU1/GTrvGOmWXXX/KK0ysvYIsik08pcwg29TLWwwfBmcY3HtDKt2x6Y=
      on:
        branch: master
